version: "3"
services:

  database:
    image: mysql
    restart: always
    container_name: MySQL
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'Eric'
      MYSQL_PASSWORD: 'String1!'
      MYSQL_ROOT_PASSWORD: 'String1!'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./database:/var/lib/mysql

  backend: #Dotnet webapi
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: backend
    command: > 
      bash -c "dotnet dev-certs https && dotnet run"
    working_dir: /app
    depends_on:
      - database
    volumes:
      - ./backend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    scale: 1
    ports:
      - 5029:5029 #HTTPS
      - 7172:7172 #HTTPS
    restart: unless-stopped


    
  frontend: #React frontend
    image: node
    container_name: frontend
    command: ["npm", "start"]
    working_dir: /app
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    scale: 1
    ports:
      - 8080:3000
    expose:
      - 3000
    restart: unless-stopped