version: "3"
services:
  # database:
  #   image: mcr.microsoft.com/mssql/server
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourPassword
  #   ports:
  #     - 1433:1433

  backend: #Dotnet webapi
    image: mcr.microsoft.com/dotnet/sdk:7.0
    container_name: backend
    command: > 
      bash -c "dotnet run"
    working_dir: /app
    # depends_on:
      # - database
    volumes:
      - ./backend2:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    scale: 1
    ports:
      # - 5029:5029 #HTTPS
      # - 7172:7172 #HTTPS
      - 8080:5197
    expose:
      - 5197
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    ports:
      - 8081:80

    
  # frontend: #React frontend
  #   image: node
  #   container_name: frontend
  #   command: ["npm", "start"]
  #   working_dir: /app
  #   # depends_on:
  #   #   - backend
  #   volumes:
  #     - ./frontend:/app
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   scale: 1
  #   ports:
  #     - 8080:3000
  #   expose:
  #     - 3000
  #   restart: unless-stopped