version: "3"
services:


  backend: #Dotnet webapi
    image: portfolio-backend
    container_name: backend
    volumes:
      - ./database:/publish/Database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8081:80
    restart: unless-stopped


    
  frontend: #React frontend
    image: node
    container_name: frontend
    command: ["npm", "start"]
    working_dir: /app
    # depends_on:
    #   - backend
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    scale: 1
    ports:
      - 8080:3000
    expose:
      - 3000
    restart: unless-stopped