version: "3"

services:
  backend: #Dotnet webapi
    image: portfolio-backend
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8081:80
    volumes:
      - ./database:/publish/Database
    
  frontend: #React frontend
    image: portfolio-frontend
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 8080:80

  Nginx-Proxy-Manager:
    container_name: Nginx
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - '80:80'
      - '8082:81'
      - '443:443'
    volumes:
      - ./Proxy/NPM/Data:/data
      - ./Proxy/NPM/letsencrypt:/etc/letsencrypt